services:
  mysql-db:
    # Trên MacOS (đặc biệt là chip M1/M2/M3), dùng image mysql:8.0-oracle hỗ trợ tốt nhất
    image: mysql:8.0-oracle 
    container_name: pthtw_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mat_khau_cua_ban
      MYSQL_DATABASE: research_management_db
    ports:
      # Map cổng 3307 của máy Mac vào cổng 3306 của Container
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: